### ISSUE TITLE
yolo dl4j show errors

### ISSUE THREAD

**Issue by badarshahzad** [jesuino/java-ml-projects#2]
I tried application to start how the yolo work but it did not run successfully.

**Scenario:**
![peek 2018-02-12 12-43](https://user-images.githubusercontent.com/19945367/36087290-77ff89ee-0ff3-11e8-9899-82e167e6d4e7.gif)

**Error Log:**
```
/usr/lib/jvm/java-8-oracle/bin/java "-javaagent:/home/badar/Downloads/Softwares/Idea Intelij/idea-IU-172.4343.14/lib/idea_rt.jar=35363:/home/badar/Downloads/Softwares/Idea Intelij/idea-IU-172.4343.14/bin" -Dfile.encoding=UTF-8 -classpath /usr/lib/jvm/java-8-oracle/jre/lib/charsets.jar:/usr/lib/jvm/java-8-oracle/jre/lib/deploy.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/cldrdata.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/dnsns.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/jaccess.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/jfxrt.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/localedata.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/nashorn.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/sunec.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/sunjce_provider.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/sunpkcs11.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/zipfs.jar:/usr/lib/jvm/java-8-oracle/jre/lib/javaws.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jce.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jfr.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jfxswt.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jsse.jar:/usr/lib/jvm/java-8-oracle/jre/lib/management-agent.jar:/usr/lib/jvm/java-8-oracle/jre/lib/plugin.jar:/usr/lib/jvm/java-8-oracle/jre/lib/resources.jar:/usr/lib/jvm/java-8-oracle/jre/lib/rt.jar:/root/IntelliJIDEAProjects/java-ml-projects/utilities/yolo-dl4j/target/classes:/root/.m2/repository/org/nd4j/nd4j-native-platform/0.9.2-SNAPSHOT/nd4j-native-platform-0.9.2-20180211.165331-1748.jar:/root/.m2/repository/org/bytedeco/javacpp-presets/openblas-platform/0.2.20-1.4/openblas-platform-0.2.20-1.4.jar:/root/.m2/repository/org/bytedeco/javacpp-presets/openblas/0.2.20-1.4/openblas-0.2.20-1.4.jar:/root/.m2/repository/org/bytedeco/javacpp-presets/openblas/0.2.20-1.4/openblas-0.2.20-1.4-android-arm.jar:/root/.m2/repository/org/bytedeco/javacpp-presets/openblas/0.2.20-1.4/openblas-0.2.20-1.4-android-x86.jar:/root/.m2/repository/org/bytedeco/javacpp-presets/openblas/0.2.20-1.4/openblas-0.2.20-1.4-linux-x86.jar:/root/.m2/repository/org/bytedeco/javacpp-presets/openblas/0.2.20-1.4/openblas-0.2.20-1.4-linux-x86_64.jar:/root/.m2/repository/org/bytedeco/javacpp-presets/openblas/0.2.20-1.4/openblas-0.2.20-1.4-linux-armhf.jar:/root/.m2/repository/org/bytedeco/javacpp-presets/openblas/0.2.20-1.4/openblas-0.2.20-1.4-linux-ppc64le.jar:/root/.m2/repository/org/bytedeco/javacpp-presets/openblas/0.2.20-1.4/openblas-0.2.20-1.4-macosx-x86_64.jar:/root/.m2/repository/org/bytedeco/javacpp-presets/openblas/0.2.20-1.4/openblas-0.2.20-1.4-windows-x86.jar:/root/.m2/repository/org/bytedeco/javacpp-presets/openblas/0.2.20-1.4/openblas-0.2.20-1.4-windows-x86_64.jar:/root/.m2/repository/org/bytedeco/javacpp-presets/mkl-platform/2018.1-1.4/mkl-platform-2018.1-1.4.jar:/root/.m2/repository/org/bytedeco/javacpp-presets/mkl/2018.1-1.4/mkl-2018.1-1.4.jar:/root/.m2/repository/org/bytedeco/javacpp-presets/mkl/2018.1-1.4/mkl-2018.1-1.4-linux-x86.jar:/root/.m2/repository/org/bytedeco/javacpp-presets/mkl/2018.1-1.4/mkl-2018.1-1.4-linux-x86_64.jar:/root/.m2/repository/org/bytedeco/javacpp-presets/mkl/2018.1-1.4/mkl-2018.1-1.4-macosx-x86_64.jar:/root/.m2/repository/org/bytedeco/javacpp-presets/mkl/2018.1-1.4/mkl-2018.1-1.4-windows-x86.jar:/root/.m2/repository/org/bytedeco/javacpp-presets/mkl/2018.1-1.4/mkl-2018.1-1.4-windows-x86_64.jar:/root/.m2/repository/org/nd4j/nd4j-native/0.9.2-SNAPSHOT/nd4j-native-0.9.2-20180211.165330-1745.jar:/root/.m2/repository/org/nd4j/nd4j-native-api/0.9.2-SNAPSHOT/nd4j-native-api-0.9.2-20180211.165351-1749.jar:/root/.m2/repository/org/nd4j/nd4j-native/0.9.2-SNAPSHOT/nd4j-native-0.9.2-20180211.115449-1731-android-arm.jar:/root/.m2/repository/org/nd4j/nd4j-native/0.9.2-SNAPSHOT/nd4j-native-0.9.2-20180211.115603-1732-android-x86.jar:/root/.m2/repository/org/nd4j/nd4j-native/0.9.2-SNAPSHOT/nd4j-native-0.9.2-20180211.130752-1739-linux-x86_64.jar:/root/.m2/repository/org/nd4j/nd4j-native/0.9.2-SNAPSHOT/nd4j-native-0.9.2-20180211.145343-1743-macosx-x86_64.jar:/root/.m2/repository/org/nd4j/nd4j-native/0.9.2-SNAPSHOT/nd4j-native-0.9.2-20180211.165330-1745-windows-x86_64.jar:/root/.m2/repository/ch/qos/logback/logback-classic/1.0.6/logback-classic-1.0.6.jar:/root/.m2/repository/ch/qos/logback/logback-core/1.0.6/logback-core-1.0.6.jar:/root/.m2/repository/org/slf4j/slf4j-api/1.6.5/slf4j-api-1.6.5.jar:/root/.m2/repository/org/deeplearning4j/deeplearning4j-core/0.9.2-SNAPSHOT/deeplearning4j-core-0.9.2-20180211.092550-409.jar:/root/.m2/repository/org/deeplearning4j/nearestneighbor-core/0.9.2-SNAPSHOT/nearestneighbor-core-0.9.2-20180211.092510-406.jar:/root/.m2/repository/org/deeplearning4j/deeplearning4j-nn/0.9.2-SNAPSHOT/deeplearning4j-nn-0.9.2-20180211.092541-409.jar:/root/.m2/repository/org/nd4j/nd4j-common/0.9.2-SNAPSHOT/nd4j-common-0.9.2-20180211.165348-1752.jar:/root/.m2/repository/com/github/stephenc/findbugs/findbugs-annotations/1.3.9-1/findbugs-annotations-1.3.9-1.jar:/root/.m2/repository/org/nd4j/nd4j-jackson/0.9.2-SNAPSHOT/nd4j-jackson-0.9.2-20180211.165354-1750.jar:/root/.m2/repository/org/nd4j/nd4j-base64/0.9.2-SNAPSHOT/nd4j-base64-0.9.2-20180211.165401-1753.jar:/root/.m2/repository/commons-net/commons-net/3.1/commons-net-3.1.jar:/root/.m2/repository/org/apache/commons/commons-math3/3.4.1/commons-math3-3.4.1.jar:/root/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar:/root/.m2/repository/org/apache/commons/commons-compress/1.8/commons-compress-1.8.jar:/root/.m2/repository/org/tukaani/xz/1.5/xz-1.5.jar:/root/.m2/repository/com/google/guava/guava/20.0/guava-20.0.jar:/root/.m2/repository/org/nd4j/nd4j-api/0.9.2-SNAPSHOT/nd4j-api-0.9.2-20180211.165359-1757.jar:/root/.m2/repository/com/github/davidmoten/flatbuffers-java/1.7.0.1/flatbuffers-java-1.7.0.1.jar:/root/.m2/repository/com/google/protobuf/protobuf-java/3.4.0/protobuf-java-3.4.0.jar:/root/.m2/repository/uk/com/robust-it/cloning/1.9.3/cloning-1.9.3.jar:/root/.m2/repository/org/objenesis/objenesis/2.1/objenesis-2.1.jar:/root/.m2/repository/org/nd4j/nd4j-buffer/0.9.2-SNAPSHOT/nd4j-buffer-0.9.2-20180211.165346-1755.jar:/root/.m2/repository/org/nd4j/nd4j-context/0.9.2-SNAPSHOT/nd4j-context-0.9.2-20180211.165438-1752.jar:/root/.m2/repository/net/ericaro/neoitertools/1.0.0/neoitertools-1.0.0.jar:/root/.m2/repository/org/reflections/reflections/0.9.10/reflections-0.9.10.jar:/root/.m2/repository/org/javassist/javassist/3.19.0-GA/javassist-3.19.0-GA.jar:/root/.m2/repository/com/google/code/findbugs/annotations/2.0.1/annotations-2.0.1.jar:/root/.m2/repository/org/apache/commons/commons-lang3/3.4/commons-lang3-3.4.jar:/root/.m2/repository/org/nd4j/jackson/0.9.2-SNAPSHOT/jackson-0.9.2-20180211.165338-1751.jar:/root/.m2/repository/org/yaml/snakeyaml/1.12/snakeyaml-1.12.jar:/root/.m2/repository/org/codehaus/woodstox/stax2-api/3.1.4/stax2-api-3.1.4.jar:/root/.m2/repository/joda-time/joda-time/2.2/joda-time-2.2.jar:/root/.m2/repository/org/projectlombok/lombok/1.16.16/lombok-1.16.16.jar:/root/.m2/repository/org/datavec/datavec-api/0.9.2-SNAPSHOT/datavec-api-0.9.2-20180209.055534-199.jar:/root/.m2/repository/org/jetbrains/annotations/13.0/annotations-13.0.jar:/root/.m2/repository/org/freemarker/freemarker/2.3.23/freemarker-2.3.23.jar:/root/.m2/repository/com/clearspring/analytics/stream/2.7.0/stream-2.7.0.jar:/root/.m2/repository/it/unimi/dsi/fastutil/6.5.7/fastutil-6.5.7.jar:/root/.m2/repository/net/sf/opencsv/opencsv/2.3/opencsv-2.3.jar:/root/.m2/repository/com/tdunning/t-digest/3.2/t-digest-3.2.jar:/root/.m2/repository/org/datavec/datavec-data-image/0.9.2-SNAPSHOT/datavec-data-image-0.9.2-20180209.055541-201.jar:/root/.m2/repository/com/github/jai-imageio/jai-imageio-core/1.3.0/jai-imageio-core-1.3.0.jar:/root/.m2/repository/com/twelvemonkeys/imageio/imageio-jpeg/3.1.1/imageio-jpeg-3.1.1.jar:/root/.m2/repository/com/twelvemonkeys/imageio/imageio-core/3.1.1/imageio-core-3.1.1.jar:/root/.m2/repository/com/twelvemonkeys/imageio/imageio-metadata/3.1.1/imageio-metadata-3.1.1.jar:/root/.m2/repository/com/twelvemonkeys/common/common-lang/3.1.1/common-lang-3.1.1.jar:/root/.m2/repository/com/twelvemonkeys/common/common-io/3.1.1/common-io-3.1.1.jar:/root/.m2/repository/com/twelvemonkeys/common/common-image/3.1.1/common-image-3.1.1.jar:/root/.m2/repository/com/twelvemonkeys/imageio/imageio-tiff/3.1.1/imageio-tiff-3.1.1.jar:/root/.m2/repository/com/twelvemonkeys/imageio/imageio-psd/3.1.1/imageio-psd-3.1.1.jar:/root/.m2/repository/com/twelvemonkeys/imageio/imageio-bmp/3.1.1/imageio-bmp-3.1.1.jar:/root/.m2/repository/org/bytedeco/javacv/1.4/javacv-1.4.jar:/root/.m2/repository/org/bytedeco/javacpp-presets/opencv/3.4.0-1.4/opencv-3.4.0-1.4.jar:/root/.m2/repository/org/bytedeco/javacpp-presets/ffmpeg/3.4.1-1.4/ffmpeg-3.4.1-1.4.jar:/root/.m2/repository/org/bytedeco/javacpp-presets/flycapture/2.11.3.121-1.4/flycapture-2.11.3.121-1.4.jar:/root/.m2/repository/org/bytedeco/javacpp-presets/libdc1394/2.2.5-1.4/libdc1394-2.2.5-1.4.jar:/root/.m2/repository/org/bytedeco/javacpp-presets/libfreenect/0.5.3-1.4/libfreenect-0.5.3-1.4.jar:/root/.m2/repository/org/bytedeco/javacpp-presets/libfreenect2/0.2.0-1.4/libfreenect2-0.2.0-1.4.jar:/root/.m2/repository/org/bytedeco/javacpp-presets/librealsense/1.12.1-1.4/librealsense-1.12.1-1.4.jar:/root/.m2/repository/org/bytedeco/javacpp-presets/videoinput/0.200-1.4/videoinput-0.200-1.4.jar:/root/.m2/repository/org/bytedeco/javacpp-presets/artoolkitplus/2.3.1-1.4/artoolkitplus-2.3.1-1.4.jar:/root/.m2/repository/org/bytedeco/javacpp-presets/flandmark/1.07-1.4/flandmark-1.07-1.4.jar:/root/.m2/repository/org/bytedeco/javacpp-presets/opencv-platform/3.4.0-1.4/opencv-platform-3.4.0-1.4.jar:/root/.m2/repository/org/bytedeco/javacpp-presets/opencv/3.4.0-1.4/opencv-3.4.0-1.4-android-arm.jar:/root/.m2/repository/org/bytedeco/javacpp-presets/opencv/3.4.0-1.4/opencv-3.4.0-1.4-android-x86.jar:/root/.m2/repository/org/bytedeco/javacpp-presets/opencv/3.4.0-1.4/opencv-3.4.0-1.4-linux-x86.jar:/root/.m2/repository/org/bytedeco/javacpp-presets/opencv/3.4.0-1.4/opencv-3.4.0-1.4-linux-x86_64.jar:/root/.m2/repository/org/bytedeco/javacpp-presets/opencv/3.4.0-1.4/opencv-3.4.0-1.4-linux-armhf.jar:/root/.m2/repository/org/bytedeco/javacpp-presets/opencv/3.4.0-1.4/opencv-3.4.0-1.4-linux-ppc64le.jar:/root/.m2/repository/org/bytedeco/javacpp-presets/opencv/3.4.0-1.4/opencv-3.4.0-1.4-macosx-x86_64.jar:/root/.m2/repository/org/bytedeco/javacpp-presets/opencv/3.4.0-1.4/opencv-3.4.0-1.4-windows-x86.jar:/root/.m2/repository/org/bytedeco/javacpp-presets/opencv/3.4.0-1.4/opencv-3.4.0-1.4-windows-x86_64.jar:/root/.m2/repository/org/bytedeco/javacpp-presets/leptonica-platform/1.74.4-1.4/leptonica-platform-1.74.4-1.4.jar:/root/.m2/repository/org/bytedeco/javacpp-presets/leptonica/1.74.4-1.4/leptonica-1.74.4-1.4.jar:/root/.m2/repository/org/bytedeco/javacpp-presets/leptonica/1.74.4-1.4/leptonica-1.74.4-1.4-android-arm.jar:/root/.m2/repository/org/bytedeco/javacpp-presets/leptonica/1.74.4-1.4/leptonica-1.74.4-1.4-android-x86.jar:/root/.m2/repository/org/bytedeco/javacpp-presets/leptonica/1.74.4-1.4/leptonica-1.74.4-1.4-linux-x86.jar:/root/.m2/repository/org/bytedeco/javacpp-presets/leptonica/1.74.4-1.4/leptonica-1.74.4-1.4-linux-x86_64.jar:/root/.m2/repository/org/bytedeco/javacpp-presets/leptonica/1.74.4-1.4/leptonica-1.74.4-1.4-linux-armhf.jar:/root/.m2/repository/org/bytedeco/javacpp-presets/leptonica/1.74.4-1.4/leptonica-1.74.4-1.4-linux-ppc64le.jar:/root/.m2/repository/org/bytedeco/javacpp-presets/leptonica/1.74.4-1.4/leptonica-1.74.4-1.4-macosx-x86_64.jar:/root/.m2/repository/org/bytedeco/javacpp-presets/leptonica/1.74.4-1.4/leptonica-1.74.4-1.4-windows-x86.jar:/root/.m2/repository/org/bytedeco/javacpp-presets/leptonica/1.74.4-1.4/leptonica-1.74.4-1.4-windows-x86_64.jar:/root/.m2/repository/org/deeplearning4j/deeplearning4j-ui-components/0.9.2-SNAPSHOT/deeplearning4j-ui-components-0.9.2-20180211.092532-407.jar:/root/.m2/repository/commons-codec/commons-codec/1.10/commons-codec-1.10.jar:/root/.m2/repository/org/deeplearning4j/deeplearning4j-zoo/0.9.2-SNAPSHOT/deeplearning4j-zoo-0.9.2-20180211.092548-407.jar:/root/.m2/repository/org/deeplearning4j/deeplearning4j-modelimport/0.9.2-SNAPSHOT/deeplearning4j-modelimport-0.9.2-20180211.092530-407.jar:/root/.m2/repository/org/bytedeco/javacpp/1.4.1-SNAPSHOT/javacpp-1.4.1-20180211.204425-14.jar:/root/.m2/repository/org/bytedeco/javacpp-presets/hdf5-platform/1.10.1-1.4/hdf5-platform-1.10.1-1.4.jar:/root/.m2/repository/org/bytedeco/javacpp-presets/hdf5/1.10.1-1.4/hdf5-1.10.1-1.4.jar:/root/.m2/repository/org/bytedeco/javacpp-presets/hdf5/1.10.1-1.4/hdf5-1.10.1-1.4-linux-x86.jar:/root/.m2/repository/org/bytedeco/javacpp-presets/hdf5/1.10.1-1.4/hdf5-1.10.1-1.4-linux-x86_64.jar:/root/.m2/repository/org/bytedeco/javacpp-presets/hdf5/1.10.1-1.4/hdf5-1.10.1-1.4-linux-ppc64le.jar:/root/.m2/repository/org/bytedeco/javacpp-presets/hdf5/1.10.1-1.4/hdf5-1.10.1-1.4-macosx-x86_64.jar:/root/.m2/repository/org/bytedeco/javacpp-presets/hdf5/1.10.1-1.4/hdf5-1.10.1-1.4-windows-x86.jar:/root/.m2/repository/org/bytedeco/javacpp-presets/hdf5/1.10.1-1.4/hdf5-1.10.1-1.4-windows-x86_64.jar org.fxapps.ml.deeplearning.yolo.YOLOApp
12:43:25.540 [Thread-3] INFO  org.deeplearning4j.zoo.ZooModel - Using cached model at /root/.deeplearning4j/tiny-yolo-voc_dl4j_inference.v1.zip
12:43:25.561 [Thread-3] INFO  org.deeplearning4j.zoo.ZooModel - Verifying download...
12:43:25.657 [Thread-3] INFO  org.deeplearning4j.zoo.ZooModel - Checksum local is 2921614094, expecting 2004171617
12:43:25.657 [Thread-3] ERROR org.deeplearning4j.zoo.ZooModel - Checksums do not match. Cleaning up files and failing...
java.lang.IllegalStateException: Pretrained model file failed checksum. If this error persists, please open an issue at https://github.com/deeplearning4j/deeplearning4j.
	at org.deeplearning4j.zoo.ZooModel.initPretrained(ZooModel.java:80)
	at org.deeplearning4j.zoo.ZooModel.initPretrained(ZooModel.java:41)
	at org.fxapps.ml.deeplearning.yolo.YOLOModel.init(YOLOModel.java:50)
	at org.fxapps.ml.deeplearning.yolo.YOLOApp.lambda$start$0(YOLOApp.java:67)
	at org.fxapps.ml.deeplearning.yolo.AppUtils.lambda$doBlockingAsyncWork$1(AppUtils.java:127)
	at org.fxapps.ml.deeplearning.yolo.AppUtils$2.call(AppUtils.java:161)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
java.lang.IllegalStateException: Pretrained model file failed checksum. If this error persists, please open an issue at https://github.com/deeplearning4j/deeplearning4j.
	at org.deeplearning4j.zoo.ZooModel.initPretrained(ZooModel.java:80)
	at org.deeplearning4j.zoo.ZooModel.initPretrained(ZooModel.java:41)
	at org.fxapps.ml.deeplearning.yolo.YOLOModel.init(YOLOModel.java:50)
	at org.fxapps.ml.deeplearning.yolo.YOLOApp.lambda$start$0(YOLOApp.java:67)
	at org.fxapps.ml.deeplearning.yolo.AppUtils.lambda$doBlockingAsyncWork$1(AppUtils.java:127)
	at org.fxapps.ml.deeplearning.yolo.AppUtils$2.call(AppUtils.java:161)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)

Process finished with exit code 0
```

**Comment by jesuino** [comment]
Hello,

Probably the model was corrupted when it was downloaded from dl4j servers.
 What I would try is:

* Find the model and delete it:
    * inside your home directory deeplearning4j creates a `.deeplearning4j` dir, inside it you should find the yolo model. The model file name is: `tiny-yolo-voc_dl4j_inference.v1.zip` Here's my model information:
~~~
[wsiqueir@wsiqueir .deeplearning4j]$ ll -h tiny-yolo-voc_dl4j_inference.v1.zip 
-rw-rw-r--. 1 wsiqueir wsiqueir 57M Jan 16 15:07 tiny-yolo-voc_dl4j_inference.v1.zip
[wsiqueir@wsiqueir .deeplearning4j]$ md5sum tiny-yolo-voc_dl4j_inference.v1.zip 
b30aa0a35da22d96cd87ff28b7598672  tiny-yolo-voc_dl4j_inference.v1.zip
~~~ 
* What I would try is: delete this model and run the example again. Hopefully deeplearning4j will download it again and this time it won't be corrupted.

Thanks and please let me know if it works.
